### ISSUE TITLE
List specific issues

### ISSUE THREAD

**Issue by SebastianZ** [Elchi3/mdn-doc-tests#1]
While the extension displays the numbers of issues, it doesn't provide any hint what those are.

Therefore it should be possible to display the specific issues of a type. E.g. for _Empty elements_ you'd then see the specific tags that are empty or for *Old 'en/' URLs' you'd see the exact URLs matching this pattern.

If possible, the line number should be listed besides them.

This could be implemented by allowing to expand the different error types through clicking on them.

Sebastian

**Comment by Elchi3** [comment]
This is great!
