### ISSUE TITLE
Allow to filter by errors and warnings

### ISSUE THREAD

**Issue by SebastianZ** [Elchi3/mdn-doc-tests#105]
As the list of tests gets longer, it gets harder to skim through the tests to see which ones have failed. Therefore an option should be added allowing to filter the results to only display tests with errors and warnings.

One possible solution could be a global option changable within the Add-ons Manager. If this filter is meant to be changed more often, there may also be some UI within the sidebar to toggle the display.

Sebastian

**Comment by Elchi3** [comment]
Yes, I think leaving out the "green" tests in the results view or sorting them to the bottom in the list is something we should investigate now that we have more and more tests. An option to always hide the "green" ones in the Add-ons manager also sounds good to me.

**Comment by SebastianZ** [comment]
Addendum: I chose the Add-ons Manager way to implement this, because changing the order of the tests may be unexpected to the user and people that don't care about the passing tests, don't need to get them displayed.

Sebastian
