### ISSUE TITLE
Disable context menu in sidebar

### ISSUE THREAD

**Issue by SebastianZ** [Elchi3/mdn-doc-tests#122]
Within the sidebar you can right-click to open the default page context menu. As it doesn't have any function in there, it should be disabled.

Sebastian

**Comment by Elchi3** [comment]
I sometimes copy something out of the sidebar. For example, I copy (partly) the match when I search where in the page the error is. While I mostly use ctrl-c, I don't know if others use the context menu and then "copy". But you are right, everything else in the menu doesn't work.

**Comment by SebastianZ** [comment]
Is there a way to remove parts from the context menu? Otherwise we'd need to find another method to create a new context menu, which only contains one item for copying.

Sebastian

**Comment by Elchi3** [comment]
Wondering if this is an upstream bug, but given that everyone is focusing on WebExtensions, I don't think it will be fixed anytime soon or at all :)

I am fine with removing as per the PR, as it would work for me personally. I just don't know how others are using it. Feeling is that it would be OK probably.

**Comment by SebastianZ** [comment]
Ok, so I let's merge it then. If you want to, you can create a new issue for introducing a copy context menu.

Btw. so far I didn't have to copy anything from the sidebar.

Sebastian
