### ISSUE TITLE
Enriching tests/invalid-macros.js with useful macros

### ISSUE THREAD

**Issue by SphinxKnight** [Elchi3/mdn-doc-tests#124]
Since the list described here https://github.com/Elchi3/mdn-doc-tests/blob/master/data/tests/invalid-macros.js might not be exhaustive. This issue has been created to complete it.

I can think of:
- LocalizationStatusInSection
- IncludeSubnav

Feel free to complete or close :)

**Comment by Elchi3** [comment]
Thanks Sphinx! :)

I am going to edit this comment during the next few days and add some more macros, that I come across.
- WebGLSidebar
- Firefox_for_developers
- EmbedGHLiveSample
- anch

**Comment by wbamberg** [comment]
I've added some in https://github.com/Elchi3/mdn-doc-tests/pull/125 :)

**Comment by SebastianZ** [comment]
@Elchi3 Looks like we can close issue #85 and continue the work on this one, right?

Sebastian

**Comment by Elchi3** [comment]
> @Elchi3 Looks like we can close issue #85 and continue the work on this one, right?

Yes, closed!

**Comment by SphinxKnight** [comment]
It seems `obsolete_header` can be added too

**Comment by SebastianZ** [comment]
PR #178 adds a few more macros, namely:
- anch
- ChromeBug
- EmbedGHLiveSample
- Firefox_for_developers
- IncludeSubnav
- InheritanceDiagram
- JSFiddleLink
- LocalizationStatusInSection
- MathMLRef
- obsolete_header
- WebGLSidebar
- WebKitBug

Sebastian

**Comment by Elchi3** [comment]
Looks like opening PRs for adding them to the list works just fine. If you don't feel like writing a PR yourself, it's also fine to open a new issue. Closing here for now. Thanks for the help everyone!
