### ISSUE TITLE
Test if the page contains 404 links

### ISSUE THREAD

**Issue by Elchi3** [Elchi3/mdn-doc-tests#126]
Documentation that contains dead links can be frustrating to the reader. Let's try to identify 404 links.
Note that MDN is a wiki and it does contain some "red" links on purpose, but I think in 90% of the cases we use macros like {{domxref}}, so this test would just be about testing <a> elements that are in the page source directly.

**Comment by SebastianZ** [comment]
Good idea, though I'm not sure if that feature should be part of the extension. This would massively slow down testing and there are already other extensions for this purpose like e.g. [LinkChecker](https://addons.mozilla.org/firefox/addon/linkchecker/) (which can only test the links after the page is saved, though).

Sebastian

**Comment by Elchi3** [comment]
This is a valid concern. I would like to experiment and see how bad the performance implications are and if there are workarounds. I could imagine to only run the link test once and not like all the other tests multiple times after a timeout. The solution could also be to highlight all links, or to have a button that opens them all in new tabs, to check them manually. When reviewing an MDN article carefully, I am going to all (external) links to make sure they still work. So, this is definitely part of "MDN doc testing" and I am curious, if there is a way to improve this part of reviewing.

**Comment by Elchi3** [comment]
https://github.com/stevenvachon/broken-link-checker looks interesting
