### ISSUE TITLE
Add test checking whether two spaces are used as indentation in code samples

### ISSUE THREAD

**Issue by SebastianZ** [Elchi3/mdn-doc-tests#129]
The MDN writing style guide says that [two spaces should be used in code examples instead of tabs](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Guidelines/Writing_style_guide#Code_sample_style_and_formatting).

So, there should be a test added, which checks that.

Sebastian

**Comment by Elchi3** [comment]
Makes total sense to test this.
Whenever we add more tests to the code samples though, I wonder if there is a way to use e.g. es-lint and to not re-invent the wheel. See issue #55.
But happy to accept a patch for this!

**Comment by SebastianZ** [comment]
Yes, this test may be replaced by a complete es-lint test in the future. Though, let's start simple.

Sebastian

**Comment by a2sheppy** [comment]
This should be a two-part test:

1. Are there any tabs? Those should be two spaces.
2. Are runs of spaces always a multiple of two spaces (possibly with an exception of lining up a continuation of a line with something above)?

**Comment by Elchi3** [comment]
Re-filed as https://github.com/mdn/doc-linter-rules/issues/27
