### ISSUE TITLE
Display a "working" indicator when scanning is in progress

### ISSUE THREAD

**Issue by a2sheppy** [Elchi3/mdn-doc-tests#131]
Sometimes the sidebar remains blank (or worse, showing old information) for a long time before updating with current errors. Add a spinny widget or progress bar that displays while scanning, so the user knows something is actually happening.

**Comment by SebastianZ** [comment]
The test suite currently only takes a few milliseconds to run. The reason why the sidebar displays old info or remains blank is that the test suite is triggered every 10 seconds independently from content changes. I've created #134 to change this.

Nontheless it's a good idea to have a throbber or a progress bar to indicate the progress of running the test suite, especially when there are more and more (long running) tests.

Sebastian

**Comment by SebastianZ** [comment]
I've added a progress bar at the top of the test results in PR #164. Note again that, while it's a good indication for long-running tests, it doesn't improve the UX in regard of the blank sidebar or outdated info. This will be improved in issue #134.

Sebastian

**Comment by SebastianZ** [comment]
Changes were backed out in PR #190 due to causing the Firefox UI to slow down/freeze as described in issue #188.

Sebastian

**Comment by SebastianZ** [comment]
This got fixed with #194.

Sebastian
