### ISSUE TITLE
If editor is open in one tab, sometimes it stays visible when switching to another MDN tab

### ISSUE THREAD

**Issue by a2sheppy** [Elchi3/mdn-doc-tests#132]
This doesn't happen all the time but it seems to happen fairly often: if I have an MDN tab open in the editor with the test sidebar open, then switch to another MDN tab that's not in the editor, the sidebar sometimes remains open.

I'll comment on this if I produce a pattern.

**Comment by SebastianZ** [comment]
The latest commits made some changes related to when the sidebar is opened. So, please check that again when @Elchi3 made a new release.

Sebastian

**Comment by SebastianZ** [comment]
With the current version in the repository I cannot reproduce this. Though there is the related issue #166.

Sebastian
