### ISSUE TITLE
Improve automatic triggering of test suite run

### ISSUE THREAD

**Issue by SebastianZ** [Elchi3/mdn-doc-tests#134]
Currently the test suite is triggered time-based every 10 seconds. This causes outdated information to be displayed due to the long delays in checking and requires the user to click the _Run tests_ button if (s)he's unpatient.

Therefore it would be better if it was triggered on content change instead. This may still require some delay to avoid triggering it on every key stroke, but it would be a timeout after the content changed.

Sebastian

**Comment by Elchi3** [comment]
I would like a visual gimmick that shows how many seconds are left until the next test run :-)
Maybe a progress bar that completes from left to right. 

It can be triggered by a content change, but I also think that even then there should be some timeout/delay.

Also, a keyboard shortcut to re-run the tests would be cool.

**Comment by SebastianZ** [comment]
> I would like a visual gimmick that shows how many seconds are left until the next test run :-)
> Maybe a progress bar that completes from left to right.
> 
> It can be triggered by a content change, but I also think that even then there should be some timeout/delay.

If it's triggered by content change, I'd assume that the timeout would be smaller than the current delay (e.g. 0.5-3 seconds). And the timeout would be reset everytime new content is added. I.e. the test suite will just be run after you stop typing.
If that's implemented that way, I assume there may be no need for a progress bar (probably not even the 'Run tests' button). But let's try out how that behaves.

> Also, a keyboard shortcut to re-run the tests would be cool.

This can be implemented separately. I created #136 for that.
Though note again, triggering the test suite run manually may not be needed at all anymore if running it automatically is smart enough.

Sebastian

**Comment by a2sheppy** [comment]
Yes, I think it should perhaps wait 2-4 seconds at least after each keystroke to see if another occurs before starting a re-run.

**Comment by SebastianZ** [comment]
I've done a first try in https://github.com/Elchi3/mdn-doc-tests/tree/automatic-test-suite-triggering.

It triggers the test suite run on tab load and switch and half a second after every `keyup` event (timeout reset on `keydown`).

It doesn't yet trigger the run automatically in all cases and the code still has some hacks, but my great goal is to make the _Run tests_ button unnecessary.

@a2sheppy, @Elchi3 Would be great if you could try it out and provide some feedback.

Sebastian

**Comment by SebastianZ** [comment]
I've improved my patch further, so the cases where you need to press the _Run tests_ button are even less now. I think it's ready to be applied, so I've created PR #206.

Further improvement can be done later to make the _Run tests_ button really redundant.

Sebastian
