### ISSUE TITLE
Add a test for checking "en-US" links in a localized page

### ISSUE THREAD

**Issue by SphinxKnight** [Elchi3/mdn-doc-tests#138]
If a localized page keeps "en-US links" (links that points to English page), the reader cannot access localized content nor see the call to action.
Thus, if the writer is translating/editing, no link should point to MDN English pages (even if the localized target document doesn't exist yet).

**Comment by SebastianZ** [comment]
I assume this is valid for all links containing locales, which differ from the current one. I mean, a French page also shouldn't contain links to a German site, or are there valid use cases for this?

> Thus, if the writer is translating/editing, no link should point to MDN English pages (even if the localized target document doesn't exist yet).

I wonder whether there's a general convention about that. So far I also translated links for inexistent localizations, though if the slug is translated, it causes problems to associate the page with the English version, right?

Sebastian

**Comment by SebastianZ** [comment]
I've created a patch for this assuming links to other locales are always invalid and that localizing even for inexistent pages is required.

Though before merging we should clarify the questions of my previous comment.

Sebastian

**Comment by Elchi3** [comment]
I think this makes sense even for inexistent pages. It is a broader problem that an association might be lost, which we can think about in another issue maybe or on the Kuma side.

**Comment by Elchi3** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1272351

**Comment by SebastianZ** [comment]
Getting an NPE on https://developer.mozilla.org/en-US/docs/Tools$edit at /tests/different-locale-links.js:12:42.

Sebastian

**Comment by SebastianZ** [comment]
Because PR #158 already got merged, I close this issue again.

Sebastian
