### ISSUE TITLE
macro-syntax-error.js does not detect {{XX("foo()"}} as an error

### ISSUE THREAD

**Issue by SphinxKnight** [Elchi3/mdn-doc-tests#141]
While editing, I found out that the test was still passing though the closing bracket was missing.
The regexp at https://github.com/Elchi3/mdn-doc-tests/blob/master/data/tests/macro-syntax-error.js#L50 should be updated but I didn't find the solution yet, hence this issue.

**Comment by SphinxKnight** [comment]
Unsure if `\{\{[^\(]+\([^\}]*[^\)]\}\}` will do. :s

**Comment by SebastianZ** [comment]
> Unsure if `\{\{[^\(]+\([^\}]*[^\)]\}\}` will do. :s

Unfortunately, that also matches valid macros like `{{XX("foo()") }}`.
I've used the more complex expression `^\{\{[^\(]+\((?:(["']).*\1|[^\)]*)*\s*\}\}$` instead, checking string parameters individually.

Sebastian

**Comment by Elchi3** [comment]
Reverted the proposed PR with b55db20ae37ecae60fbbb74a791668ad38b431ba

The proposed regex caused Fx 46 on Ubuntu 16.04 to freeze.

**Comment by SebastianZ** [comment]
I've created #157, which uses a simpler approach than the previous patch, which should (hopefully) be correct now.

Sebastian
