### ISSUE TITLE
Add WebRTCSidebar to list of allowed macros

### ISSUE THREAD

**Issue by a2sheppy** [Elchi3/mdn-doc-tests#144]
I'm going to list here some macros that should be on the list of macros that pass the "invalid macros" test.

WebRTCSidebar
RFC

More may come later.

**Comment by SebastianZ** [comment]
Should I keep this issue open? Note that those may also be added in issue #124.

Sebastian

**Comment by a2sheppy** [comment]
I assume we can close it now that the PR is merged; I'll open a new one
if I find more macros to add, or can I just do a PR without an issue? I
don't know how strictly this project is run.

---

_From:_ Sebastian Zartner
_Sent:_ Wednesday, Apr 13, 2016 3:47:40 AM EDT
_To:_ Elchi3/mdn-doc-tests
_Cc:_ Eric Shepherd
_Subject:_ [Elchi3/mdn-doc-tests] Add WebRTCSidebar to list of allowed
macros (#144)

> Should I keep this issue open?

## 

-- Sheppy

**Comment by SebastianZ** [comment]
> I assume we can close it now that the PR is merged; I'll open a new one
> if I find more macros to add, or can I just do a PR without an issue? I
> don't know how strictly this project is run.

IMO it's fine to cover all macro additions in #124 (and create several PRs for it).
The rule of thumb for this project is: Small things don't require an issue, bigger ones should have one.

Sebastian
