### ISSUE TITLE
Test on-site links to sections to see if they exist

### ISSUE THREAD

**Issue by a2sheppy** [Elchi3/mdn-doc-tests#145]
When there are links to pages on MDN which exist, but to sections on those pages which don't, we should put up a warning.

**Comment by SebastianZ** [comment]
Good point! Though I'd say that's an error rather than a warning, no?

As a first step, I'd say to only check anchor links on the **current** page.
Checking other pages requires asynchronous handling, which needs to be implemented first and should be done in a separate issue.

Sebastian

**Comment by a2sheppy** [comment]
Yeah, should be an error.

-- Sheppy

**Comment by Elchi3** [comment]
Re-filed as https://github.com/mdn/doc-linter-rules/issues/18
