### ISSUE TITLE
Elements containing images are incorrectly recognized as empty

### ISSUE THREAD

**Issue by SebastianZ** [Elchi3/mdn-doc-tests#154]
When an element only contains an image or another replaced element and doesn't have any text contents, it is currently incorrectly recognized as empty.

Sebastian

**Comment by Elchi3** [comment]
I think `<p><br></p>` is something we want to avoid / to be shown as error. There are many people who edit MDN docs and think that texts need more space, so they are adding these constructs.

I think this change will not show this case anymore, which I think would be a regression.

**Comment by SebastianZ** [comment]
`<br>` and `<wbr>` are explicitly excluded from the whitelist and they are also tested in the unit test.
I.e. `<p><br></p>` will still be shown as error.

Sebastian

**Comment by Elchi3** [comment]
I should read the code more carefully :-) Thanks!

**Comment by SebastianZ** [comment]
Don't worry, I could equally have missed it.

Sebastian
