### ISSUE TITLE
Word counter and reading time estimation

### ISSUE THREAD

**Issue by Elchi3** [Elchi3/mdn-doc-tests#17]
Would be cool to know what the word count and reading time of the page you are editing is. Pages that are too long are a burden for our localizers.

**Comment by Elchi3** [comment]
Given we now (or soon with PR #34 merged) have "warnings" (yellow) and "errors" (red), this could be "info" (blue).

**Comment by Elchi3** [comment]
Looked at counting words a little bit with a simple Regexp, bit it seemed to be quite slow.

Needs to be tested for performance on long articles like https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Signaling_and_video_calling

**Comment by SebastianZ** [comment]
> Given we now (or soon with PR #34 merged) have "warnings" (yellow) and "errors" (red), this could be "info" (blue).

Generally I like the idea about adding info messages. Though I wonder whether too long texts should be marked as warning instead.

> Looked at counting words a little bit with a simple Regexp, bit it seemed to be quite slow.

What was your expression? I assume this may work as a very simple measurement:

``` javascript
content.replace(/<\/?.+?>/g, "").match(/\w+/g).length
```

Question is, what should be the rules for counting?

Sebastian

**Comment by Elchi3** [comment]
I rebased my experiment and pushed it as branch "issue-17" so that you can have a look. For me it still slow on long pages, though I haven't got the "unresponsive script" dialog with these regexes.

**Comment by SebastianZ** [comment]
Yes, it's also really slow for me. It needs to be investigated, why, because executing the regexp above within Firebug was pretty fast.

If you want to do that, please assign yourself to that issue, otherwise I'll take it at some point.

Sebastian

**Comment by SebastianZ** [comment]
I could improve the speed of the text a lot, as we now only need to check the text content and don't have to remove the HTML tags first. See #165.

Sebastian
