### ISSUE TITLE
Add test for <pre> with class 'eval'

### ISSUE THREAD

**Issue by SebastianZ** [Elchi3/mdn-doc-tests#173]
A test should be added checking whether a `<pre>` tag has `eval` as class name. Instead of `eval` people should use `brush:...`. For blocks not needing syntax highlighting they should use `brush: plain`.

This test could be added to the existing 'pre-without-class' test.

Sebastian

**Comment by Elchi3** [comment]
Re-filed as https://github.com/mdn/doc-linter-rules/issues/26
