### ISSUE TITLE
Merge languages-macro test into invalid-macros test

### ISSUE THREAD

**Issue by SebastianZ** [Elchi3/mdn-doc-tests#179]
Now that we have a test checking for invalid macros and the list of tests getting longer and longer, we may want to merge the {{languages}} macro test and the {{JSRef}} parameters test into it to save some vertical space.

@Elchi3 Do you agree or do you think this may rather cause people to miss them in the bunch of other invalid macro warnings?

Sebastian

**Comment by Elchi3** [comment]
Sounds good to me, especially the language macro case.

Note that there are still many macros with parameters where would rather have no parameters in order to be able to maintain them better. So, I think there could be more than just the JSRref case where we would want to discourage parameters.

**Comment by SebastianZ** [comment]
> Note that there are still many macros with parameters where would rather have no parameters in order to be able to maintain them better. So, I think there could be more than just the JSRref case where we would want to discourage parameters.

Sure. Those macros can easily be added. If you already have some in mind, please file an issue, so we don't forget them.

Sebastian

**Comment by SebastianZ** [comment]
As the jsref-with-params test is somewhat different to the invalid-macros test, I believe now it's ok to keep it and broaden it, see issue #186.

Sebastian
