### ISSUE TITLE
WebExtension blockers

### ISSUE THREAD

**Issue by Elchi3** [Elchi3/mdn-doc-tests#181]
At some point in the future, this add-on could be a WebExtension. I would like to use this issue to collect what is currently preventing us to rewrite this add-on as a WebExtension add-on.
- There is no sidebar in WebExtensions

**Comment by Elchi3** [comment]
See also this excellent page, that is currently being written by Will. https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_from_the_Add-on_SDK

**Comment by wbamberg** [comment]
Bug for WebExtensions sidebar API: https://bugzilla.mozilla.org/show_bug.cgi?id=1208596

**Comment by Elchi3** [comment]
If Mozilla is accepted for GSOC, I will mentor this project. 
https://wiki.mozilla.org/Community:SummerOfCode17:Brainstorming#Mozilla_Developer_Network

**Comment by SebastianZ** [comment]
FYI, the [WebExtension sidebar API](https://bugzilla.mozilla.org/show_bug.cgi?id=1208596) is now available (didn't try it myself yet, though).

Sebastian

**Comment by SebastianZ** [comment]
I've now filed #231 for the work to create the WebExtension. @Elchi3 I assume, this issue can be closed now, right?

Sebastian

**Comment by Elchi3** [comment]
I assume that they are no other blockers, but I guess that we can only identify more blockers once we actually start the work, or do more research.

**Comment by SebastianZ** [comment]
Note that while there's now a sidebar API, it seems it only allows to open the sidebar via a toolbar button. We need to open it based on the given URL, though, so I've created [bug 1343817](https://bugzilla.mozilla.org/show_bug.cgi?id=1343817) asking for the related API.

Sebastian

**Comment by wbamberg** [comment]
Thanks for filing @SebastianZ . I'm sure you won't be the only one asking for this :).

**Comment by SebastianZ** [comment]
So, hopefully we'll see this getting implemented soon, then! 😃 

Sebastian
