### ISSUE TITLE
Re-add spellchecking

### ISSUE THREAD

**Issue by Elchi3** [Elchi3/mdn-doc-tests#182]
In commit fc947a85929e66ba25103bd5dc9c924be51852d0, the snippet that enables spellchecking was removed. I miss it now when editing :(

I proposed several times to enable this on the Kuma-side, but I got disagreement in the discussions. Can I have it back here at least?

**Comment by Elchi3** [comment]
Maybe I am missing something on how to activate this in a different way. Why did you remove this code, @SebastianZ ?

**Comment by SebastianZ** [comment]
I agree with you that spellchecking should be part of Kuma. I guess the reason was that it's a bit complicated to add it back and I tend to think that it's not MDN docs tester's duty to add that feature.
Anyway, I've added it back in #183.

Sebastian
