### ISSUE TITLE
Have blue info results expanded by default?

### ISSUE THREAD

**Issue by Elchi3** [Elchi3/mdn-doc-tests#187]
I'm using the collapsed view and I hide passed tests. However, the blue article length result is of course collapsed then as well. I wonder if we want info boxes to be expanded by default.

**Comment by SebastianZ** [comment]
As long as the text is not too long so that the warning is shown, I normally ignore the info box.
Should we add an option to expand it by default?

Sebastian

**Comment by Elchi3** [comment]
Nah, it isn't too important. I learned to ignore it, when it is not a warning, too.
