### ISSUE TITLE
Add-on slows down the browser when executing tests.

### ISSUE THREAD

**Issue by Elchi3** [Elchi3/mdn-doc-tests#188]
I feel like since the progress bar is implemented the add-on slows down or even freezes my entire Firefox whenever the animation takes place. Has anyone else noticed this? I don't feel like releasing a new version with this, but I am not sure I can provide any more details or STR.

**Comment by SebastianZ** [comment]
You're right. I didn't realize this before, but there is obviously a slowdown, especially when the hardware is slow.
We should investigate why, but for now I'd say, back the changes out and reopen issue #131, so you can make the release.

Sebastian

**Comment by Elchi3** [comment]
Done in https://github.com/Elchi3/mdn-doc-tests/pull/190

Note that I will take a working day or two to use and test the latest master version again before releasing anything.

**Comment by SebastianZ** [comment]
> Done in #190

Ok, I've reopened issue #131.

> Note that I will take a working day or two to use and test the latest master version again before releasing anything.

Take your time! We're not in a hurry. Let me know if I can help you with anything.

Sebastian
