### ISSUE TITLE
Sign XPI

### ISSUE THREAD

**Issue by SebastianZ** [Elchi3/mdn-doc-tests#19]
Signing extensions is required since Firefox 43.0 and in Firefox 44.0 the option to deactivate the requirement is removed.

Therefore the extension should be signed to be used. The steps to do so are [described on MDN](https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm#jpm_sign) (where else :-) ).

Sebastian

**Comment by Elchi3** [comment]
I released a first signed version of the add-on, so that it works again in Firefox 43. https://github.com/Elchi3/mdn-doc-tests/releases.
I guess in the future we can also release and distribute on amo.
