### ISSUE TITLE
Current master branch is still slow

### ISSUE THREAD

**Issue by Elchi3** [Elchi3/mdn-doc-tests#191]
I backed out the progress bar, but that didn't really fix things for more in terms of freezing the browser / making Firefox unresponsive when the tests run. I need to investigate more, but don't have much time right now. Would like to hear feedback from other master branch users as well. Is the HEAD revision here working nicely for you?

**Comment by SebastianZ** [comment]
I'll investigate the next days, but I'm a bit busy at the moment, too.

Sebastian

**Comment by SebastianZ** [comment]
Tested (using Nightly 51 with e10s enabled) on my slow laptop and my PC at work and I cannot reproduce that slowness on the master branch. In both cases it's taking only some milliseconds now to run the tests.

Does anyone else experience a freeze while the test suite runs? @Elchi3 Please test again once you have time again. Could it be that you accidentally tested the wrong branch or so?

Sebastian

**Comment by SebastianZ** [comment]
Hmm, on my PC at work it even stays responsive using revision https://github.com/Elchi3/mdn-doc-tests/commit/b483254565550fc514186628e28cbb6e71d5af2a...

Need to check at home again.

Sebastian

**Comment by SebastianZ** [comment]
I think I've found the culprit. See PR #192. @Elchi3 Please try it out any let me know whether that fixes the problem for you.

This change probably also allows us to add the progress bar back. So, @Elchi3, in case the patch fixes the issue, please create an issue for that.

Sebastian

**Comment by SebastianZ** [comment]
> This change probably also allows us to add the progress bar back. So, @Elchi3, in case the patch fixes the issue, please create an issue for that.

I've already done it, see #193.

Sebastian
