### ISSUE TITLE
Make extension jpm compatible

### ISSUE THREAD

**Issue by SebastianZ** [Elchi3/mdn-doc-tests#20]
cfx for packaging and running add-ons got replaced by jpm. To get the extension to work with jpm, its package.json needs to be adjusted.

jpm requires the package.json to contain:
1. a proper `id`.
2. a proper `version`.
3. a `main` property as entry point.

Sebastian

**Comment by Elchi3** [comment]
This was merged and creating a signed jpm extension worked for me.
