### ISSUE TITLE
Fix failing Travis CI properly

### ISSUE THREAD

**Issue by SebastianZ** [Elchi3/mdn-doc-tests#200]
In #198 the failing Travis CI runs were fixed by setting the Firefox version to 47 to avoid the add-on signing requirement. Though that's only a temporary solution, because we're stuck with that version.

We need to find a way to get the test suite run with the current version. I see three possible solutions:
1. Use unbranded Firefox versions (which allow to run unsigned add-ons)
   
   [Travis CI currently does not allow to use those versions](https://docs.travis-ci.com/user/firefox/), though. Adding support for them is filed at https://github.com/travis-ci/travis-ci/issues/4064.
2. Use DevEdition or Nightly versions (which allow to run unsigned add-ons)
   
   Same as above. Travis CI currently does not allow to run those versions. I filed https://github.com/travis-ci/travis-ci/issues/6543 for adding support for them.
3. Sign the add-on
   
   The add-on might be automatically signed before testing. Though it needs to be investigated first if that's even possible.

Sebastian

**Comment by Elchi3** [comment]
We're not planning to release a new add-on SDK version of the doc-tester and we won't fix travis of this repo. I'll disable travis likely.
