### ISSUE TITLE
Summary even marked as error when it's not at the top of the page

### ISSUE THREAD

**Issue by SebastianZ** [Elchi3/mdn-doc-tests#208]
Guides like [_Grids_](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Grids) within the Learning Area have a summary at the bottom of the article, which provide a conclusion of the previous text.

Those occurrences of 'Summary' headlines must not be marked as errors.

Sebastian

**Comment by Elchi3** [comment]
Re-filed as https://github.com/mdn/doc-linter-rules/issues/25
