### ISSUE TITLE
Allow 'Summary' on CSS articles

### ISSUE THREAD

**Issue by SebastianZ** [Elchi3/mdn-doc-tests#209]
Currently the 'Summary' headings need to be kept on CSS articles in order for the [MDN tooltip](https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_CSS#Get_help_for_CSS_properties) to work.

To be able to remove those headings we depend on [bug 1201600](https://bugzilla.mozilla.org/show_bug.cgi?id=1201600). (Note that I just proposed a solution for it.)

So, until that bug is fixed, we may mark the 'Summary' headings in CSS articles as warnings instead of errors or even ignore them completely.

@Elchi3 what do you think?

Sebastian

**Comment by a2sheppy** [comment]
The tooltip should be simply pulling the SEO summary from the CSS article, no? That's what we do for most things, anyway.

**Comment by Elchi3** [comment]
Summary headings should go away on CSS pages, too, because now the devtools tooltip is gone.
