### ISSUE TITLE
Require hidden explanatory text for macros that rely on data

### ISSUE THREAD

**Issue by Elchi3** [Elchi3/mdn-doc-tests#210]
If a contributor edits a page and wants to change compatibility data or CSS property data they will only see macros like {{Compat}} or {{cssinfo}}. They will wonder where those macros are and how they are getting the information, so that they can contribute to it.

That's why for {{Compat}} we have started to put an edit-only text into the doc, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy$edit

>  The compatibility table in this page is generated from structured data. If you'd like to contribute to the data, please check out https://github.com/mdn/browser-compat-data and send us a pull request.

This extension should force us to always provide  <p class="hidden"> text when we use macros that deal with data. These macros are:
- compat
- cssinfo
- csssyntax
- WebExtBrowserCompat
- ...

**Comment by SebastianZ** [comment]
Should there be a single comment for all macros or one comment for each?

Sebastian
