### ISSUE TITLE
Make rules l10n aware

### ISSUE THREAD

**Issue by SebastianZ** [Elchi3/mdn-doc-tests#22]
There are some rules, which only target the English version of an article. They don't work on localized pages. These rules are:
- Old 'en/' URLs
- Summary heading
- 'Example:' headings
- API syntax headlines

Those should be adjusted to also work correctly on localizations or be hidden on them.

Sebastian

**Comment by Elchi3** [comment]
Re-filed as https://github.com/mdn/doc-linter-rules/issues/15
