### ISSUE TITLE
Test suite run after loading a page provides wrong results

### ISSUE THREAD

**Issue by SebastianZ** [Elchi3/mdn-doc-tests#220]
Directly after loading a page the test suite is run. Though this run causes an error and returns incorrect results.

Error shown in browser console:

> Object { _errorType: "Error", message: "text.match(...) is null", fileName: "resource://gre/modules/commonjs/too…", lineNumber: 18, stack: "checkArticleLength@resource://gre/m…", name: "TypeError" }  core.js:106

Sebastian

**Comment by Elchi3** [comment]
Development continues as a WebExtension and the rules are developed in an own repository.
Please file against https://github.com/mdn/doc-linter-webextension or https://github.com/mdn/doc-linter-rules if you encounter this again.
