### ISSUE TITLE
Add check for 'document_saved=true' parameter within MDN URLs

### ISSUE THREAD

**Issue by SebastianZ** [Elchi3/mdn-doc-tests#221]
After saving a page `document_saved=true` is added as parameter to the URL.
This parameter should not appear within links to other pages.

So, a test should be added checking for that parameter.

_Note: This issue will be gone once [bug 1298399](https://bugzilla.mozilla.org/show_bug.cgi?id=1298399) is fixed._

Sebastian

**Comment by Elchi3** [comment]
bug 1298399 is fixed, lets hope this will never appear again :)
