### ISSUE TITLE
“Different locale links“ error for non-localized resource

### ISSUE THREAD

**Issue by sideshowbarker** [Elchi3/mdn-doc-tests#225]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input has a reference to https://mdn.mozillademos.org/files/3251/mozactionhint.png that causes the documentation tester to emit a “Different locale links“ error.

It’s not clear if or how the URL can be changed to something that won’t cause the documentation tester to emit an error.

**Comment by Elchi3** [comment]
Fixed in https://github.com/mdn/doc-linter-rules/pull/22
