### ISSUE TITLE
Add CompatEdge to accepted macros for browser compat tables

### ISSUE THREAD

**Issue by a2sheppy** [Elchi3/mdn-doc-tests#232]
This macro was added fairly recently to support the work being done to add Edge compatibility information to MDN. But it is flagged as an error by the tester. We need to add it to the supported macros.

**Comment by a2sheppy** [comment]
It looks like it's on the list... so I'm not sure why it's flagged as an error.

**Comment by Elchi3** [comment]
All compat macros besides {{compat}} should be disallowed. See https://github.com/mdn/doc-linter-rules/issues/13
