### ISSUE TITLE
Missing updateURL element

### ISSUE THREAD

**Issue by Elchi3** [Elchi3/mdn-doc-tests#27]
Validation Results for mdn_documentation_tester-0.2.0-fx.xpi from addons.mozilla.org:

Your add-on does not specify an update URL. This means that it will be impossible for you to serve updates to this add-on which are not listed publicly on addons.mozilla.org.

**Comment by SebastianZ** [comment]
So, there are two solutions:
1. Add the extension to AMO. (see #33)
2. Manually [create an update URL](https://developer.mozilla.org/en-US/Add-ons/Install_Manifests#updateURL).

Note that these solutions do not exclude each other.

Sebastian

**Comment by Elchi3** [comment]
I think this is okay as is with the AMO upload / distribution.
