### ISSUE TITLE
Check against some more API reference wording conventions

### ISSUE THREAD

**Issue by Elchi3** [Elchi3/mdn-doc-tests#29]
The <h3> headlines after an <h2>Syntax</h2> headline on a method page have the following rules:
- “Return value” and not “Returns”,
- "Exceptions" and not "Errors" or "Errors thrown",
- Order: “Parameters", then “Return value”, then “Exceptions”

https://groups.google.com/forum/#!topic/mozilla.mdn/sUDN2kB433k

**Comment by SebastianZ** [comment]
Example pages are:

'Returns': https://developer.mozilla.org/en-US/docs/Web/API/DOMApplication/launch
'Errors': https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder/start
'Returns' and wrong order: https://developer.mozilla.org/en-US/docs/Web/API/Document/caretPositionFromPoint

Sebastian
