### ISSUE TITLE
Add MDN documentation tester to AMO

### ISSUE THREAD

**Issue by SebastianZ** [Elchi3/mdn-doc-tests#33]
The MDN documentation tester should get uploaded to addons.mozilla.org to make it easier to find it and profit from AMOs infrastructure.

Sebastian

**Comment by Elchi3** [comment]
Added to AMO. Awaiting review now. https://addons.mozilla.org/en-US/firefox/addon/mdn-documentation-tester/

**Comment by SebastianZ** [comment]
Congrats to your first official AMO version of MDN documentation tester! :+1: 

Sebastian
