### ISSUE TITLE
Allow to fix issues automatically

### ISSUE THREAD

**Issue by SebastianZ** [Elchi3/mdn-doc-tests#4]
The Add-on should be capable of fixing the issues it lists automatically - at least some of them.

This could be implemented by adding a button besides each issue item.

Sebastian

**Comment by SebastianZ** [comment]
Regarding the UI I see three (non-exclusive) possibilities to implement this:
- A button to fix all errors at once
- An option besides each test (headline) to fix all of its errors
- An option besides each match to fix only that one error

@Elchi3 Which option(s) would you choose? Any other ideas?

Sebastian

**Comment by Elchi3** [comment]
I would say let's implement or prototype the easiest (fastest) variant and iterate from there.

**Comment by SebastianZ** [comment]
Technically I assume they should all require more or less the same effort, though I assume the option with only one button is the one people would likely use the most.

So, I'll start with that one then. (And we can create follow-up issues if we feel it's not enough.)

Sebastian

**Comment by SebastianZ** [comment]
This issue obviously requires some more work. So I suggest to do a release now without it.

Sebastian
