### ISSUE TITLE
Allow l10n

### ISSUE THREAD

**Issue by SebastianZ** [Elchi3/mdn-doc-tests#41]
It should be possible to translate the strings within the extension into other languages.

Sebastian

**Comment by Elchi3** [comment]
Note:
"There's no support for content scripts or CSS files: at the moment, you can only localize strings appearing in JavaScript files that can require() SDK modules and in HTML." 
https://developer.mozilla.org/en-US/Add-ons/SDK/Tutorials/l10n#Limitations

https://github.com/Elchi3/mdn-doc-tests/blob/master/data/doctests.js is a content script.

**Comment by SebastianZ** [comment]
Thanks for the hint. I already read about that.
I am already working on this one and I have an easy workaround for that. Expect my pull request in the coming hours. :-)

Sebastian

**Comment by Elchi3** [comment]
Nicely done!
