### ISSUE TITLE
Macro test: White space false positive {{ foo("bar") }}

### ISSUE THREAD

**Issue by Elchi3** [Elchi3/mdn-doc-tests#43]
This case {{ foo("bar") }} is currently marked as a failure, but shouldn't.
Personally, I don't like the spaces there, but I don't think this should be an error.

**Comment by SebastianZ** [comment]
Oh, sorry! I didn't realize you already created an issue for that. I've fixed this in issue #46.

Sebastian

**Comment by Elchi3** [comment]
No worries and thanks for the fix :+1:
