### ISSUE TITLE
Test MDN code examples against es-lint?

### ISSUE THREAD

**Issue by Elchi3** [Elchi3/mdn-doc-tests#55]
The quality of the MDN code examples could be improved, if we run them against es-lint, for example. 
Also, there are many plug-ins available, including this one by @mozfreddyb https://github.com/mozfreddyb/eslint-plugin-no-unsafe-innerhtml, which prevents insecure use of innerHTML.

**Comment by a2sheppy** [comment]
We could also look at using something like JSCS to validate sample code style. That would be cool -- especially if we were able to automatically fix at least basic problems.

**Comment by SebastianZ** [comment]
> …if we were able to automatically fix at least basic problems.

Note that fixing problems automatically is covered in issue #4 and I just started working on that.

Sebastian
