### ISSUE TITLE
Test for <span> tags should be refined

### ISSUE THREAD

**Issue by SebastianZ** [Elchi3/mdn-doc-tests#6]
Currently all uses of `<span>` tags are counted as errors. Though sometimes `<span>` tags may be allowed within the articles like for marking SEO content.

See e.g. https://developer.mozilla.org/en-US/docs/Web/CSS/will-change.

So the extension should ignore those cases.

Sebastian

**Comment by Elchi3** [comment]
Resolved by PR #24
