### ISSUE TITLE
Test 'headlinesWording' fails while editing in formatted view

### ISSUE THREAD

**Issue by SebastianZ** [Elchi3/mdn-doc-tests#61]
The 'headlinesWording' test fails finding errors while editing the article in the formatted view. You need to switch to the source view and back to the formatted view to see the errors.

Sebastian

**Comment by Elchi3** [comment]
This is interesting. I have seen this with preLinesTooLong, too, and switching between source mode and WYSIWYG fixed the false positive there, too.

**Comment by SebastianZ** [comment]
I missed to create a unit test for that. Let me add one once the other PRs are merged. I reopen this issue to not forget about that.

Sebastian
