### ISSUE TITLE
Add test coverage checking

### ISSUE THREAD

**Issue by SebastianZ** [Elchi3/mdn-doc-tests#64]
A tool for unit test coverage should be included.

Sebastian

**Comment by Elchi3** [comment]
Disclaimer: I have never been familiar with "front-end tooling". However, I researched a bit and found some stuff: 
- First, https://coveralls.io offers these badges and I saw this service on other repositories already.
- There is js/node.js support for it: https://github.com/nickmerwin/node-coveralls
- Looks like `jpm test` provides no lcov output or any instrumenting, so you would need an instrumenter tool like istanbul-jpm for lcov output: https://github.com/freaktechnik/istanbul-jpm

**Comment by Elchi3** [comment]
Won't happen for the add-on-sdk based add-on anymore.
