### ISSUE TITLE
Test 'preLineTooLong ' fails while editing in formatted view

### ISSUE THREAD

**Issue by Elchi3** [Elchi3/mdn-doc-tests#66]
Similar to issue #61 

The 'preLineTooLong' test fails finding errors while editing the article in the formatted view. You need to switch to the source view and back to the formatted view to see the errors.

**Comment by Elchi3** [comment]
Does this occur to other tests, too? Can we fix this more generally?

**Comment by SebastianZ** [comment]
> Does this occur to other tests, too?

I'll have a look.

> Can we fix this more generally?

Not sure. The simplest would probably be to add a function that is removing all `<br>`s and call it from all tests where this is happening.

Sebastian

**Comment by SebastianZ** [comment]
> > Can we fix this more generally?
> 
> Not sure. The simplest would probably be to add a function that is removing all `<br>`s and call it from all tests where this is happening.

Here I needed to replace the `<br>` by a line break, while for the other issue I needed to remove it.
I guess we can solve it by always replacing it by a line break, though then the test cases will have to be adjusted.

I think I'll refactor all that in a separate step.

Sebastian
