### ISSUE TITLE
Create Milestone for version 1.0

### ISSUE THREAD

**Issue by SebastianZ** [Elchi3/mdn-doc-tests#71]
I think it would be good to group some issues within a milestone allowing to have a target to work towards.

Depending on the definition of what a 1.0 release is for you, @Elchi3, I'd add the following issues to it:
#4, #17, #22, #49, #67, #72

Sebastian

**Comment by Elchi3** [comment]
The last pre-release contains some bugs, so for a 1.0 I would give a bit more testing time. Wouldn't mind to go 0.4pre first or even do another pre-release after that as 0.5pre. I think we can also start by saying which larger items will not make it into the next release to get a better feeling.

**Comment by SebastianZ** [comment]
Of course I am expecting other releases before 1.0. Version 1.0 would just mean to be a big release including the most important features.

Btw. 0.4 should be done when the four pending PRs are merged. That should also be the first "real" release with (hopefully) no complaints by the AMO reviewers.

Sebastian

**Comment by SebastianZ** [comment]
Ok, so let's create Milestone 1.0 then.

Sebastian

**Comment by SebastianZ** [comment]
Here it is: [Milestone Version 1.0](https://github.com/Elchi3/mdn-doc-tests/milestones)

Of course, things may still be added or removed depending on what is considered as a must-have for version 1.0.

Sebastian
