### ISSUE TITLE
Add icon

### ISSUE THREAD

**Issue by SebastianZ** [Elchi3/mdn-doc-tests#72]
The extension should have a nice icon to be recognizable.

I assume it's ok to reuse the MDN logo for that like Sheppy did for his [_MDN: Save With Comment Hotkey_ extension](https://github.com/a2sheppy/mdn-save-with-comment), or are there any legal issues?

Sebastian

**Comment by Elchi3** [comment]
Nope, the icon should be okay to use. Good idea!

**Comment by SebastianZ** [comment]
For reference, here's the SVG source file plus three PNGs in different sizes created from it:

[icon.zip](https://github.com/Elchi3/mdn-doc-tests/files/97178/icon.zip)
