### ISSUE TITLE
Add test for allowed macros

### ISSUE THREAD

**Issue by SebastianZ** [Elchi3/mdn-doc-tests#85]
A test should check whether the macros used within the page actually exist.

This requires to make an XHR for each used macro. As this may cause a lot of requests and only a simple response would be enough, this may require some platform support.

Sebastian

**Comment by Elchi3** [comment]
To help the macro clean-up project, I would suggest adding a whitelist of macros to this add-on and check from there.

**Comment by SebastianZ** [comment]
Fine for me. So, once we have a list, please post it here.

Sebastian

**Comment by Elchi3** [comment]
There is no definitive list yet and I don't know when we will have such a list. It could probably be a list that can grow in this repository over time. I think even if the whole macro system is cleaned up, there will be new macros every now and then or refactorings that lead to removals or additions. I am going to start by proposing these 50 macros as a whitelist. We can put them somewhere and set up the test to resolve this issue.

Template:GroupData
Template:InterfaceData
Template:L10n:Common
Template:L10n:CompatTable
Template:L10n:JavaScript
Template:L10n:SVG
Template:Promote-MDN
Template:releaseGecko
Template:SidebarUtilities
Template:SVGData
Template:WebExtensionSidebar
Template:CSSData
Template:L10n:CSS
Template:DocStatus
Template:CanvasSidebar
Template:DefaultAPISidebar
Template:deprecated_header
Template:htmlattrdef
Template:deprecated_inline
Template:obsolete_inline
Template:experimental_inline
Template:htmlattrxref
Template:xref
Template:ReadOnlyInline
Template:page
Template:non-standard_inline
Template:event
Template:geckoRelease
Template:cssinfo
Template:Glossary
Template:JsSidebar
Template:property_prefix
Template:PreviousNext
Template:EmbedLiveSample
Template:SeeCompatTable
Template:interface
Template:XULElem
Template:non-standard_header
Template:XULAttr
Template:gecko
Template:CSSRef
Template:bug
Template:cssxref
Template:JSRef
Template:HTMLElement
Template:jsxref
Template:APIRef
Template:domxref
Template:SpecName
Template:Spec2

**Comment by SebastianZ** [comment]
> There is no definitive list yet and I don't know when we will have such a list. It could probably be a list that can grow in this repository over time. I think even if the whole macro system is cleaned up, there will be new macros every now and then or refactorings that lead to removals or additions.

Sure, that's why I would prefer an automatic solution, but having a whitelist is a good first step.

> I am going to start by proposing these 50 macros as a whitelist. We can put them somewhere and set up the test to resolve this issue.

Thank you for the list! For now, I think they are best placed within the test file itself. A future version may do a server request for getting the list.

Sebastian

**Comment by SebastianZ** [comment]
Testing them on the first site I realized that there are already missing some, 'csssyntax', 'CompatibilityTable' and all the 'Compat*' macros. I'll add those, too.

Sebastian

**Comment by SebastianZ** [comment]
Also, all the '*_inline' macros like 'experimental_inline' or 'fx_minversion_inline' are missing.
Should those be added, too?

Sebastian

**Comment by SebastianZ** [comment]
I added the test (with its matches as warnings), though as stated above, I think it's still missing a bunch of macros.
Therefore I didn't create a PR yet.

Sebastian

**Comment by Elchi3** [comment]
> Sure, that's why I would prefer an automatic solution, but having a whitelist is a good first step.

I think my point is that "list of all macros" will maybe never be "list of whitelisted macros", because concepts change over time. For example, the compat macros are obsolete once the BC project is shipped to MDN, other things will change too and macros will need to be changed, replaced or removed. Anyway, let's explore this with a whitelist for now, we can always adapt to new realities.

> Also, all the '*_inline' macros like 'experimental_inline' or 'fx_minversion_inline' are missing.
> Should those be added, too?

I think this makes sense, yes. We can become stricter later on. (I think a rule is that there should be no fx_minversion in Web/\* docs [because you have compat info for that], but it is fine to be used elsewhere)

**Comment by SebastianZ** [comment]
> > Sure, that's why I would prefer an automatic solution, but having a whitelist is a good first step.
> 
> I think my point is that "list of all macros" will maybe never be "list of whitelisted macros", because concepts change over time. For example, the compat macros are obsolete once the BC project is shipped to MDN, other things will change too and macros will need to be changed, replaced or removed. Anyway, let's explore this with a whitelist for now, we can always adapt to new realities.

I get your point. Though note that the initial idea of this issue was to only check for macro existence, independently of whether its use is recommended or not. So, those are two different use cases.

> > Also, all the '*_inline' macros like 'experimental_inline' or 'fx_minversion_inline' are missing.
> > Should those be added, too?
> 
> I think this makes sense, yes. We can become stricter later on. (I think a rule is that there should be no fx_minversion in Web/\* docs [because you have compat info for that], but it is fine to be used elsewhere)

My statement was wrong. `experimental_inline` and other main `*_inline` macros are there, only `optional_inline` was missing.
I've added it and some others I considered worth to add.

Sebastian
