### ISSUE TITLE
Improve test for <pre> w/o class to suggest 'syntaxbox' where applicable

### ISSUE THREAD

**Issue by SebastianZ** [Elchi3/mdn-doc-tests#86]
When the _Formal syntax_ or _Syntax_ section has a `<pre>` block without `class` attribute, the 'preWithoutClass' test should provide a hint to add `syntaxbox` as class name.

Sebastian

**Comment by a2sheppy** [comment]
There are cases in which we don't use classes on `<pre>` though, such as one-liner code snippets and all over the place in the XPCOM interface reference, wherein we have always historically used classless `<pre>` for the function prototypes in order to make them as copy/pasteable as possible (this would no longer be an issue except the line numbers make things unnecessarily cluttered; I just now noticed that they're being inserted there despite no class, which isn't supposed to be the case). See https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIDragService#endDragSession%28%29 for example.

**Comment by SebastianZ** [comment]
> There are cases in which we don't use classes on `<pre>` though, such as one-liner code snippets 

Note that the test for `<pre>` not using a class was already in the first version of the extension. So, @Elchi3 what was the reason to add it in the first place?

Having said that, in cases of one-liner code I am always using `<code>` instead of `<pre>`.

> and all over the place in the XPCOM interface reference, wherein we have always historically used classless `<pre>` for the function prototypes in order to make them as copy/pasteable as possible

In cases where no highlighting is wished, I am using `eval` as class name (basically to avoid the extension from nagging).
In the case of the interface references like the one you mention, @a2sheppy , I think `syntaxbox` as class name is the better choice (which should be added to the formatting styles, btw.).

I'm [asking on the mailing list about it's usage](https://groups.google.com/forum/#!topic/mozilla.dev.mdc/vSLx6QJT1cI). You may add there that `<pre>` without class should not add line numbers (if we agree that there are valid use cases for `<pre>` without class).

Sebastian

**Comment by Elchi3** [comment]
> Note that the test for `<pre>` not using a class was already in the first version of the extension. So, @Elchi3 what was the reason to add it in the first place?

`<pre>` not using a class is in almost every scenario a forgotten syntax highlighter setting, imo.

> In cases where no highlighting is wished, I am using `eval` as class name (basically to avoid the extension from nagging).

In my opinion: Don't do that. The add-on is not better than human judgment. It is totally fine to ignore warnings or errors. I see no point in adding `eval`. Actually, it is an old, unused CSS class which usage we should probably discourage. (our front-end devs will be happy about every obscure css class that we avoid)

I agree that one-liner are more likely to use `<code>` instead.

>  XPCOM interface reference, wherein we have always historically used classless `<pre>`

Historically :-)
The XPCOM example @a2sheppy mentions better uses `syntaxbox` in my opinion, too.

**Comment by SebastianZ** [comment]
> > In cases where no highlighting is wished, I am using `eval` as class name (basically to avoid the extension from nagging).
> 
> In my opinion: Don't do that. The add-on is not better than human judgment. It is totally fine to ignore warnings or errors. I see no point in adding `eval`. Actually, it is an old, unused CSS class which usage we should probably discourage. (our front-end devs will be happy about every obscure css class that we avoid)

Ok, so then there may still be some use cases for `<pre>` without class. Need to find those cases again, but I assume they must be related to things like e.g. console output.
We [still use it in many places](https://developer.mozilla.org/en-US/search?css_classnames=eval), though.

Sebastian

**Comment by a2sheppy** [comment]
I do not disagree. I just don't have time to go fix them all right now.
There are many thousands of them. :)

---

_From:_ Florian Scholz
_Sent:_ Friday, Feb 26, 2016 6:01:28 AM EST
_To:_ Elchi3/mdn-doc-tests
_Cc:_ Eric Shepherd
_Subject:_ [mdn-doc-tests] Improve test for <pre> w/o class to suggest
'syntaxbox' where applicable (#86)

> The XPCOM example @a2sheppy https://github.com/a2sheppy mentions
> better uses |syntaxbox| in my opinion, too.

**Comment by SebastianZ** [comment]
> > In cases where no highlighting is wished, I am using `eval` as class name (basically to avoid the extension from nagging).
> 
> In my opinion: Don't do that. The add-on is not better than human judgment. It is totally fine to ignore warnings or errors. I see no point in adding `eval`. Actually, it is an old, unused CSS class which usage we should probably discourage. (our front-end devs will be happy about every obscure css class that we avoid)

Ok, so I won't add `eval` anymore. From reading more about the highlighter, I guess the right class would be `brush: plain`, anyway.

If we have cases where it is valid to use `<pre>`s without class — i.e. blocks without syntax highlighting or line numbers — (and [Will stated](https://groups.google.com/d/msg/mozilla.dev.mdc/vSLx6QJT1cI/zsWgTN-BHgAJ) that he [may already have found one](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Your_second_WebExtension#Testing_it_out)), then the test matches should be turned into warnings or the test may be removed completely.
Rule of thumb: The extension should never show an error where there isn't one. I.e. error (red) = real error that needs to be fixed, warning (yellow) = possible error or small issue that needs to be checked.

> > >  XPCOM interface reference, wherein we have always historically used classless `<pre>`
> > 
> > Historically :-)
> > The XPCOM example @a2sheppy mentions better uses `syntaxbox` in my opinion, too.
> 
> I do not disagree. I just don't have time to go fix them all right now. There are many thousands of them. :)

No time? I thought you'd fix them all right away. ;-p Just kidding, but we should try to fix them when we stumble over them.

Sebastian

**Comment by SebastianZ** [comment]
Because the 'wrong-syntax-class' test already provides proper info in this case, I close this issue.
Regarding the case for `<pre>` without class, see issue #174.

Sebastian
