### ISSUE TITLE
AMO review feedback: Add a call to removeEventListener

### ISSUE THREAD

**Issue by Elchi3** [Elchi3/mdn-doc-tests#89]
> This version has been approved for the public.
> 
> Please note the following for the next update:
> 1) If the addEventListener() (or JQuery .on) is used once (e.g. for 'load', 'DOMContentLoaded'), it is good practice to removeEventListener() (or JQuery .off) as soon as its function is called and free the resources.
> elem.addEventListener(event, myfunction, false);
> function myfunction() {
>   elem.removeEventListener(event, myfunction, false); // remove listener, no longer needed
>   // rest of the function code
> }
> 
> elem.addEventListener(event, function myfunction(event){
>     elem.removeEventListener(event, myfunction, false); // remove listener, no longer needed
>     // rest of the function code
> },false);
> 
> Thank you for your contribution.

**Comment by SebastianZ** [comment]
There was only one listener, which needed to be removed again after it is triggered.
As this was a very small change, I didn't create a branch or PR for it.

Sebastian
