### ISSUE TITLE
Enhancement: Analyze the content when creating a new translation

### ISSUE THREAD

**Issue by SphinxKnight** [Elchi3/mdn-doc-tests#95]
The add-on is not active when creating a new page in a locale for an existing English page though the MDN UI is pretty much the same.

Since the change should be pretty simple, I'll make a PR soon.

**Comment by SebastianZ** [comment]
Thank you for the PR. I've improved the regular expression a little bit after merging.

This functionality is missing a unit test, so I've created issue #97.

@Elchi3 I've assigned myself to this issue even when the changes were done by @SphinxKnight to signal that I am the responsible for the merge. Let me know whether that's ok.

Sebastian
