### ISSUE TITLE
Matches are indistinguishable

### ISSUE THREAD

**Issue by SebastianZ** [Elchi3/mdn-doc-tests#99]
For some test matches it is a bit hard to distinguish them. See this example:

![undestinguishable matches](https://cloud.githubusercontent.com/assets/958943/13069341/1b8cd59c-d484-11e5-9301-839d699b9181.png)

Therefore, matches should be highlighted when they are hovered.

Sebastian

**Comment by SebastianZ** [comment]
According to the comments to PR #101 I've now created two branches:
- [issue-99-even-odd using altering background colors](https://github.com/Elchi3/mdn-doc-tests/tree/issue-99-even-odd)
- [issue-99-borders using borders and paddings](https://github.com/Elchi3/mdn-doc-tests/tree/issue-99-borders)

I need to say I prefer borders and paddings over altering background colors. Altering the colors makes the UI somewhat twitchy (hope that's the right word for it).
@Elchi3 what do you think?

Sebastian

**Comment by Elchi3** [comment]
I like the borders, but 1px is very tiny for my eyes. I tested it with 2px and that would work for me:

![2px-borders](https://cloud.githubusercontent.com/assets/349114/13110669/b26ffb08-d581-11e5-8faf-5b1df30938c4.png)

**Comment by SebastianZ** [comment]
I agree, two pixels as border look better. I've created PR #109.

Sebastian
